-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A
    JOIN FOOD_ORDER B
    ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE B.PRODUCE_DATE>=STR_TO_DATE('2022-05-01','%Y-%m-%d') AND B.PRODUCE_DATE<=STR_TO_DATE('2022-05-31','%Y-%m-%d')
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID